// Auto-generated by scripts/weekly-keiba-update.mjs
// Do not edit manually.

import type { TrainingInsight } from "./trainingInsights";

export const TRAINING_DATA_GENERATED_AT = "2026-03-22T22:17:19.971Z";

export const GENERATED_TRAINING_INSIGHTS: TrainingInsight[] = [
  {
    "courseId": "nakayama-turf-1800",
    "horseId": "1",
    "score": 2,
    "note": "Strong final split and explicit positive tone.",
    "source": "https://www.sponichi.co.jp/gamble/news/2026/02/26/kiji/20260225s00004048348000c.html",
    "publishedAt": "2026-02-26",
    "channel": "news"
  },
  {
    "courseId": "nakayama-turf-1800",
    "horseId": "2",
    "score": 1,
    "note": "Commented as improved movement after prior stiffness.",
    "source": "https://www.sponichi.co.jp/gamble/news/2026/02/26/kiji/20260225s00004048351000c.html",
    "publishedAt": "2026-02-26",
    "channel": "news"
  },
  {
    "courseId": "nakayama-turf-1200",
    "horseId": "3",
    "score": 2,
    "note": "Headlined as very sharp work and high readiness.",
    "source": "https://www.sponichi.co.jp/gamble/news/2026/02/26/kiji/20260225s00004048356000c.html",
    "publishedAt": "2026-02-26",
    "channel": "news"
  },
  {
    "courseId": "hanshin-turf-1600",
    "horseId": "1",
    "score": 2,
    "note": "Workout article highlights very good finishing response.",
    "source": "https://www.sponichi.co.jp/gamble/news/2026/02/26/kiji/20260225s00004048339000c.html",
    "publishedAt": "2026-02-26",
    "channel": "news"
  }
];

export const GENERATED_X_TRAINING_OVERRIDES: TrainingInsight[] = [];
