// Auto-generated by scripts/update-race-volatility.mjs
// Do not edit manually.

import type { RaceVolatility } from "./raceVolatility";

export const RACE_VOLATILITY_GENERATED_AT = "2026-06-08T05:52:37.339Z";

export const GENERATED_RACE_VOLATILITY: Record<string, RaceVolatility> = {
  "nakayama-turf-1800": {
    "courseId": "nakayama-turf-1800",
    "upsetScore": 62,
    "reason": "中山記念は1番人気の勝率が高すぎず、ヒモ荒れも一定数ある。",
    "source": "https://www.jra.go.jp/keiba/thisweek/2026/0301_1/"
  },
  "nakayama-turf-1200": {
    "courseId": "nakayama-turf-1200",
    "upsetScore": 68,
    "reason": "オーシャンSは二桁人気の好走・勝利例があり波乱を含む。",
    "source": "https://www.jra.go.jp/keiba/thisweek/2026/0228_1/"
  },
  "hanshin-turf-1600": {
    "courseId": "hanshin-turf-1600",
    "upsetScore": 75,
    "reason": "チューリップ賞は近年高配当決着が見られ、波乱傾向。",
    "source": "https://www.jra.go.jp/keiba/thisweek/2026/0301_2/"
  }
};
