// AUTO-GENERATED by scripts/calibration-report.mjs --write-coefficients
// 確定済み本命実績に対するロジスティック再校正係数。手編集しないこと。
// 再生成: node scripts/calibration-report.mjs --write-coefficients

export const CALIBRATION_VERSION = "cal-2026-06-10-n223";

export const CALIBRATION_META = Object.freeze({
  fittedAt: "2026-06-10T14:55:35.335Z",
  sampleSize: 223,
  dateRange: { from: "2026-03-06", to: "2026-06-06" },
  method: "logistic recalibration p_cal = sigmoid(a + b * logit(p_model)), fit on settled honmei outcomes",
  winLogLoss: { rawModel: 0.6699, rawMarket: 0.5998, calibrated: 0.583 },
  placeLogLoss: { rawModel: 0.6604, calibrated: 0.635 },
});

export const WIN_CALIBRATION = Object.freeze({ a: -0.7356, b: 3.3361 });
export const PLACE_CALIBRATION = Object.freeze({ a: -0.7527, b: 1.2899 });

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function recalibrate(prob, coef) {
  const p = clamp(Number(prob), 0.01, 0.99);
  const z = coef.a + coef.b * Math.log(p / (1 - p));
  return 1 / (1 + Math.exp(-z));
}

export function calibrateWinProb(prob) {
  return recalibrate(prob, WIN_CALIBRATION);
}

export function calibratePlaceProb(prob) {
  return recalibrate(prob, PLACE_CALIBRATION);
}
