// AUTO-GENERATED by scripts/calibration-report.mjs --write-coefficients
// 確定済み本命実績に対するロジスティック再校正係数。手編集しないこと。
// 再生成: node scripts/calibration-report.mjs --write-coefficients

export const CALIBRATION_VERSION = "cal-2026-06-10-n231";

export const CALIBRATION_META = Object.freeze({
  fittedAt: "2026-06-10T15:22:56.436Z",
  sampleSize: 231,
  dateRange: { from: "2026-03-06", to: "2026-06-07" },
  method: "logistic recalibration p_cal = sigmoid(a + b * logit(p_model)), fit on settled honmei outcomes",
  winLogLoss: { rawModel: 0.6712, rawMarket: 0.6069, calibrated: 0.5873 },
  placeLogLoss: { rawModel: 0.6619, calibrated: 0.6357 },
});

export const WIN_CALIBRATION = Object.freeze({ a: -0.7442, b: 3.114 });
export const PLACE_CALIBRATION = Object.freeze({ a: -0.7165, b: 1.2378 });

// 複勝オッズの線形近似 (確定済み複勝的中の実払戻に OLS フィット)。
// 旧近似 odds*0.35+1.0 は実払戻比 1.4-1.6 倍過大だった。
export const PLACE_ODDS_MODEL = Object.freeze({ slope: 0.1649, intercept: 0.8981, sampleSize: 145 });

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function recalibrate(prob, coef) {
  const p = clamp(Number(prob), 0.01, 0.99);
  const z = coef.a + coef.b * Math.log(p / (1 - p));
  return 1 / (1 + Math.exp(-z));
}

export function calibrateWinProb(prob) {
  return recalibrate(prob, WIN_CALIBRATION);
}

export function calibratePlaceProb(prob) {
  return recalibrate(prob, PLACE_CALIBRATION);
}

export function estimatePlaceOdds(odds) {
  const value = Number(odds);
  if (!(value > 0)) return 1.0;
  return Math.max(1.0, value * PLACE_ODDS_MODEL.slope + PLACE_ODDS_MODEL.intercept);
}
