// Auto-generated from data/weekly-races.json
// Do not edit manually.

import type { RunningStyle } from "./types";

export interface GeneratedHorseSeed {
  id: string;
  name: string;
  jockey: string;
  trainer?: string;
  runningStyle: RunningStyle;
  gateNumber: number;
  sex: "M" | "F";
  weight: number;
  favoriteCount: number;
  xBuzzScore: number;
  predictionCount: number;
  realOdds: number;
  oddsSource: string;
  speed: number;
  stamina: number;
  power: number;
  guts: number;
  trainingScore: number;
  recentFormScore: number;
  recentAverageFinish: number;
  recentTimeIndex: number;
  lastRaceGradeScore: number;
  lastRaceGradeLabel: string;
  lastRaceDistance: number;
  distanceChange: number;
  condition: number;
}

export interface GeneratedRaceMeta {
  courseId: string;
  raceId: string;
  label: string;
  grade: string;
  day: string;
  venue: string;
  venueKey: string;
  surface: "Turf" | "Dirt";
  distance: number;
  straightLength: number;
  hashtag: string;
  hasRace: boolean;
  oddsSource: string;
}

export interface GeneratedRaceFinisher {
  position: number;
  horseId?: string;
  externalHorseId?: string;
  gateNumber: number;
  horseNumber: number;
  name: string;
  jockey: string;
  finishTime: string;
  margin: string;
  popularity: number;
  odds: number;
}

export interface GeneratedRaceResult {
  updatedAt: string;
  winnerHorseId?: string;
  winnerHorseName?: string;
  top3HorseIds: string[];
  top3HorseNames: string[];
  finishers: GeneratedRaceFinisher[];
}

export interface GeneratedRaceReview {
  updatedAt: string;
  summary: string;
  xPostText: string;
  reasons: string[];
}

export interface GeneratedReviewRace extends GeneratedRaceMeta {
  date: string;
  archivedAt?: string;
  result?: GeneratedRaceResult;
  review?: GeneratedRaceReview;
  horses: GeneratedHorseSeed[];
}

export const GENERATED_WEEKLY_RACES: GeneratedRaceMeta[] = [
  {
    "courseId": "nakayama-turf-1800-202606020311",
    "raceId": "202606020311",
    "label": "中山牝馬Ｓ 出馬表",
    "grade": "G3",
    "day": "Sat",
    "venue": "中山",
    "venueKey": "nakayama",
    "surface": "Turf",
    "distance": 1800,
    "straightLength": 310,
    "hashtag": "#中山牝馬Ｓ出馬表",
    "hasRace": true,
    "oddsSource": "official"
  },
  {
    "courseId": "nakayama-turf-2000-202606020411",
    "raceId": "202606020411",
    "label": "弥生賞ディープ記念 出馬表",
    "grade": "G2",
    "day": "Sun",
    "venue": "中山",
    "venueKey": "nakayama",
    "surface": "Turf",
    "distance": 2000,
    "straightLength": 310,
    "hashtag": "#弥生賞ディープ記念出馬表",
    "hasRace": true,
    "oddsSource": "official"
  },
  {
    "courseId": "hanshin-turf-1400-202609010511",
    "raceId": "202609010511",
    "label": "フィリーズレビュー 出馬表",
    "grade": "G2",
    "day": "Sat",
    "venue": "阪神",
    "venueKey": "hanshin",
    "surface": "Turf",
    "distance": 1400,
    "straightLength": 473.6,
    "hashtag": "#フィリーズレビュー出馬表",
    "hasRace": true,
    "oddsSource": "official"
  }
];

export const GENERATED_WEEKLY_HORSES_MAP: Record<string, GeneratedHorseSeed[]> = {
  "nakayama-turf-1800-202606020311": [
    {
      "id": "1",
      "name": "クリノメイ",
      "jockey": "横山典",
      "trainer": "須貝",
      "runningStyle": "Sashi",
      "gateNumber": 1,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 253,
      "xBuzzScore": 0,
      "predictionCount": 36,
      "realOdds": 36.7,
      "oddsSource": "official",
      "speed": 56,
      "stamina": 60,
      "power": 56,
      "guts": 60,
      "trainingScore": 0,
      "recentFormScore": -1.2,
      "recentAverageFinish": 7.6,
      "recentTimeIndex": -5,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "2",
      "name": "ビヨンドザヴァレー",
      "jockey": "菱田",
      "trainer": "橋口",
      "runningStyle": "Nige",
      "gateNumber": 2,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 309,
      "xBuzzScore": 0,
      "predictionCount": 41,
      "realOdds": 28.8,
      "oddsSource": "official",
      "speed": 63,
      "stamina": 55,
      "power": 58,
      "guts": 57,
      "trainingScore": 0,
      "recentFormScore": -1.4,
      "recentAverageFinish": 7.8,
      "recentTimeIndex": -3.3,
      "lastRaceGradeScore": 2,
      "lastRaceGradeLabel": "OP",
      "lastRaceDistance": 1800,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "3",
      "name": "エセルフリーダ",
      "jockey": "武藤",
      "trainer": "武藤",
      "runningStyle": "Senko",
      "gateNumber": 3,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 487,
      "xBuzzScore": 0,
      "predictionCount": 56,
      "realOdds": 15.3,
      "oddsSource": "official",
      "speed": 81,
      "stamina": 77,
      "power": 79,
      "guts": 81,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 5,
      "recentTimeIndex": -0.4,
      "lastRaceGradeScore": 1.5,
      "lastRaceGradeLabel": "3Win",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "4",
      "name": "パラディレーヌ",
      "jockey": "岩田望",
      "trainer": "千田",
      "runningStyle": "Sashi",
      "gateNumber": 4,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 2217,
      "xBuzzScore": 0,
      "predictionCount": 81,
      "realOdds": 5.3,
      "oddsSource": "official",
      "speed": 89,
      "stamina": 89,
      "power": 87,
      "guts": 90,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 4.3,
      "recentTimeIndex": 0.8,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 2200,
      "distanceChange": -400,
      "condition": 5
    },
    {
      "id": "5",
      "name": "ボンドガール",
      "jockey": "岩田康",
      "trainer": "手塚久",
      "runningStyle": "Senko",
      "gateNumber": 5,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 857,
      "xBuzzScore": 0,
      "predictionCount": 60,
      "realOdds": 13,
      "oddsSource": "official",
      "speed": 85,
      "stamina": 85,
      "power": 86,
      "guts": 83,
      "trainingScore": 0,
      "recentFormScore": 3.4,
      "recentAverageFinish": 7,
      "recentTimeIndex": 2.6,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "6",
      "name": "アンリーロード",
      "jockey": "石川",
      "trainer": "茶木",
      "runningStyle": "Senko",
      "gateNumber": 6,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 49,
      "xBuzzScore": 0,
      "predictionCount": 12,
      "realOdds": 218.9,
      "oddsSource": "official",
      "speed": 60,
      "stamina": 57,
      "power": 58,
      "guts": 59,
      "trainingScore": 0,
      "recentFormScore": -5,
      "recentAverageFinish": 10.8,
      "recentTimeIndex": -0.4,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "7",
      "name": "フレミングフープ",
      "jockey": "杉原",
      "trainer": "友道",
      "runningStyle": "Senko",
      "gateNumber": 7,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 656,
      "xBuzzScore": 0,
      "predictionCount": 53,
      "realOdds": 17.2,
      "oddsSource": "official",
      "speed": 86,
      "stamina": 85,
      "power": 84,
      "guts": 85,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 2.4,
      "recentTimeIndex": 0,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "8",
      "name": "レディーヴァリュー",
      "jockey": "団野",
      "trainer": "小林",
      "runningStyle": "Senko",
      "gateNumber": 8,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 72,
      "xBuzzScore": 0,
      "predictionCount": 18,
      "realOdds": 77.9,
      "oddsSource": "official",
      "speed": 77,
      "stamina": 76,
      "power": 74,
      "guts": 74,
      "trainingScore": 0,
      "recentFormScore": 0.6,
      "recentAverageFinish": 4.5,
      "recentTimeIndex": -0.9,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "9",
      "name": "ステレンボッシュ",
      "jockey": "ルメール",
      "trainer": "宮田",
      "runningStyle": "Sashi",
      "gateNumber": 9,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 327,
      "xBuzzScore": 0,
      "predictionCount": 46,
      "realOdds": 23.4,
      "oddsSource": "official",
      "speed": 64,
      "stamina": 68,
      "power": 64,
      "guts": 67,
      "trainingScore": 0,
      "recentFormScore": -5,
      "recentAverageFinish": 11.5,
      "recentTimeIndex": 0.5,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 2200,
      "distanceChange": -400,
      "condition": 5
    },
    {
      "id": "10",
      "name": "アンゴラブラック",
      "jockey": "戸崎圭",
      "trainer": "尾関",
      "runningStyle": "Senko",
      "gateNumber": 10,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 4486,
      "xBuzzScore": 0,
      "predictionCount": 86,
      "realOdds": 4.2,
      "oddsSource": "official",
      "speed": 86,
      "stamina": 87,
      "power": 89,
      "guts": 86,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 1.4,
      "recentTimeIndex": 0.7,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "11",
      "name": "フィールシンパシー",
      "jockey": "横山琉",
      "trainer": "小島",
      "runningStyle": "Senko",
      "gateNumber": 11,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 82,
      "xBuzzScore": 0,
      "predictionCount": 12,
      "realOdds": 136.2,
      "oddsSource": "official",
      "speed": 65,
      "stamina": 62,
      "power": 65,
      "guts": 61,
      "trainingScore": 0,
      "recentFormScore": -4.9,
      "recentAverageFinish": 10.8,
      "recentTimeIndex": 1,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "12",
      "name": "ポルカリズム",
      "jockey": "三浦",
      "trainer": "中内田",
      "runningStyle": "Sashi",
      "gateNumber": 12,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 301,
      "xBuzzScore": 0,
      "predictionCount": 44,
      "realOdds": 25.2,
      "oddsSource": "official",
      "speed": 88,
      "stamina": 90,
      "power": 88,
      "guts": 90,
      "trainingScore": 0,
      "recentFormScore": 4.3,
      "recentAverageFinish": 6,
      "recentTimeIndex": 4.4,
      "lastRaceGradeScore": 1.5,
      "lastRaceGradeLabel": "3Win",
      "lastRaceDistance": 1600,
      "distanceChange": 200,
      "condition": 5
    },
    {
      "id": "13",
      "name": "エリカエクスプレス",
      "jockey": "武豊",
      "trainer": "杉山晴",
      "runningStyle": "Sashi",
      "gateNumber": 13,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 1357,
      "xBuzzScore": 0,
      "predictionCount": 80,
      "realOdds": 5.5,
      "oddsSource": "official",
      "speed": 71,
      "stamina": 72,
      "power": 72,
      "guts": 71,
      "trainingScore": 0,
      "recentFormScore": -3.2,
      "recentAverageFinish": 8.8,
      "recentTimeIndex": 0.7,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 2200,
      "distanceChange": -400,
      "condition": 5
    },
    {
      "id": "14",
      "name": "ニシノティアモ",
      "jockey": "津村",
      "trainer": "上原佑",
      "runningStyle": "Senko",
      "gateNumber": 14,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 1955,
      "xBuzzScore": 0,
      "predictionCount": 83,
      "realOdds": 4.8,
      "oddsSource": "official",
      "speed": 89,
      "stamina": 89,
      "power": 90,
      "guts": 89,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 1,
      "recentTimeIndex": 0.9,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "15",
      "name": "ケリフレッドアスク",
      "jockey": "佐々木",
      "trainer": "藤原",
      "runningStyle": "Sashi",
      "gateNumber": 15,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 77,
      "xBuzzScore": 0,
      "predictionCount": 23,
      "realOdds": 61.4,
      "oddsSource": "official",
      "speed": 72,
      "stamina": 76,
      "power": 72,
      "guts": 75,
      "trainingScore": 0,
      "recentFormScore": -2,
      "recentAverageFinish": 7.5,
      "recentTimeIndex": 0.7,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 2200,
      "distanceChange": -400,
      "condition": 5
    },
    {
      "id": "16",
      "name": "レーゼドラマ",
      "jockey": "丹内",
      "trainer": "辻野",
      "runningStyle": "Sashi",
      "gateNumber": 16,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 332,
      "xBuzzScore": 0,
      "predictionCount": 54,
      "realOdds": 17,
      "oddsSource": "official",
      "speed": 60,
      "stamina": 63,
      "power": 62,
      "guts": 62,
      "trainingScore": 0,
      "recentFormScore": -0.2,
      "recentAverageFinish": 11,
      "recentTimeIndex": -1.8,
      "lastRaceGradeScore": 2,
      "lastRaceGradeLabel": "OP",
      "lastRaceDistance": 2000,
      "distanceChange": -200,
      "condition": 5
    }
  ],
  "nakayama-turf-2000-202606020411": [
    {
      "id": "1",
      "name": "ステラスペース",
      "jockey": "武藤",
      "trainer": "武藤",
      "runningStyle": "Senko",
      "gateNumber": 1,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 395,
      "xBuzzScore": 0,
      "predictionCount": 60,
      "realOdds": 12.9,
      "oddsSource": "official",
      "speed": 90,
      "stamina": 85,
      "power": 89,
      "guts": 89,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 3.4,
      "recentTimeIndex": 1.1,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "2",
      "name": "メイショウソラリス",
      "jockey": "角田和",
      "trainer": "角田",
      "runningStyle": "Senko",
      "gateNumber": 2,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 78,
      "xBuzzScore": 0,
      "predictionCount": 32,
      "realOdds": 43.2,
      "oddsSource": "official",
      "speed": 72,
      "stamina": 69,
      "power": 71,
      "guts": 73,
      "trainingScore": 0,
      "recentFormScore": -0.4,
      "recentAverageFinish": 5.7,
      "recentTimeIndex": -0.8,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "3",
      "name": "コスモギガンティア",
      "jockey": "矢野貴",
      "trainer": "河津裕",
      "runningStyle": "Sashi",
      "gateNumber": 3,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 60,
      "xBuzzScore": 0,
      "predictionCount": 25,
      "realOdds": 57.1,
      "oddsSource": "official",
      "speed": 76,
      "stamina": 79,
      "power": 75,
      "guts": 74,
      "trainingScore": 0,
      "recentFormScore": 4.8,
      "recentAverageFinish": 4.5,
      "recentTimeIndex": -2.9,
      "lastRaceGradeScore": 2.5,
      "lastRaceGradeLabel": "L",
      "lastRaceDistance": 1600,
      "distanceChange": 400,
      "condition": 5
    },
    {
      "id": "4",
      "name": "ライヒスアドラー",
      "jockey": "佐々木",
      "trainer": "上原佑",
      "runningStyle": "Oikomi",
      "gateNumber": 4,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 1881,
      "xBuzzScore": 0,
      "predictionCount": 93,
      "realOdds": 3.2,
      "oddsSource": "official",
      "speed": 84,
      "stamina": 93,
      "power": 90,
      "guts": 89,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 2,
      "recentTimeIndex": 0.8,
      "lastRaceGradeScore": 4,
      "lastRaceGradeLabel": "G2",
      "lastRaceDistance": 1800,
      "distanceChange": 200,
      "condition": 5
    },
    {
      "id": "5",
      "name": "タイダルロック",
      "jockey": "三浦",
      "trainer": "武井",
      "runningStyle": "Senko",
      "gateNumber": 5,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 703,
      "xBuzzScore": 0,
      "predictionCount": 73,
      "realOdds": 7.4,
      "oddsSource": "official",
      "speed": 85,
      "stamina": 84,
      "power": 82,
      "guts": 81,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 3.7,
      "recentTimeIndex": -0.9,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "6",
      "name": "アドマイヤクワッズ",
      "jockey": "坂井",
      "trainer": "友道",
      "runningStyle": "Sashi",
      "gateNumber": 6,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 3874,
      "xBuzzScore": 0,
      "predictionCount": 99,
      "realOdds": 2.4,
      "oddsSource": "official",
      "speed": 86,
      "stamina": 93,
      "power": 90,
      "guts": 89,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 1.7,
      "recentTimeIndex": 4.6,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 1600,
      "distanceChange": 400,
      "condition": 5
    },
    {
      "id": "7",
      "name": "モウエエデショー",
      "jockey": "原田和",
      "trainer": "萱野",
      "runningStyle": "Oikomi",
      "gateNumber": 7,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 23,
      "xBuzzScore": 0,
      "predictionCount": 15,
      "realOdds": 89.4,
      "oddsSource": "official",
      "speed": 63,
      "stamina": 69,
      "power": 65,
      "guts": 66,
      "trainingScore": 0,
      "recentFormScore": 3,
      "recentAverageFinish": 7.4,
      "recentTimeIndex": -3,
      "lastRaceGradeScore": 0,
      "lastRaceGradeLabel": "Maiden",
      "lastRaceDistance": 1800,
      "distanceChange": 200,
      "condition": 5
    },
    {
      "id": "8",
      "name": "バステール",
      "jockey": "川田",
      "trainer": "斉藤崇",
      "runningStyle": "Senko",
      "gateNumber": 8,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 932,
      "xBuzzScore": 0,
      "predictionCount": 79,
      "realOdds": 5.8,
      "oddsSource": "official",
      "speed": 87,
      "stamina": 82,
      "power": 84,
      "guts": 82,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 1.5,
      "recentTimeIndex": 1.8,
      "lastRaceGradeScore": 0,
      "lastRaceGradeLabel": "Maiden",
      "lastRaceDistance": 2000,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "9",
      "name": "アメテュストス",
      "jockey": "大野",
      "trainer": "加藤士",
      "runningStyle": "Oikomi",
      "gateNumber": 9,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 135,
      "xBuzzScore": 0,
      "predictionCount": 44,
      "realOdds": 25.3,
      "oddsSource": "official",
      "speed": 80,
      "stamina": 85,
      "power": 83,
      "guts": 86,
      "trainingScore": 0,
      "recentFormScore": 2.7,
      "recentAverageFinish": 3.8,
      "recentTimeIndex": 0.8,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 2000,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "10",
      "name": "バリオス",
      "jockey": "高杉",
      "trainer": "武幸",
      "runningStyle": "Senko",
      "gateNumber": 10,
      "sex": "M",
      "weight": 57,
      "favoriteCount": 204,
      "xBuzzScore": 0,
      "predictionCount": 54,
      "realOdds": 16.9,
      "oddsSource": "official",
      "speed": 75,
      "stamina": 75,
      "power": 77,
      "guts": 75,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 1,
      "recentTimeIndex": -1.5,
      "lastRaceGradeScore": 0,
      "lastRaceGradeLabel": "Maiden",
      "lastRaceDistance": 2000,
      "distanceChange": 0,
      "condition": 5
    }
  ],
  "hanshin-turf-1400-202609010511": [
    {
      "id": "1",
      "name": "フルールジェンヌ",
      "jockey": "永島",
      "trainer": "鈴木孝",
      "runningStyle": "Sashi",
      "gateNumber": 1,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 70,
      "xBuzzScore": 0,
      "predictionCount": 14,
      "realOdds": 92.3,
      "oddsSource": "official",
      "speed": 80,
      "stamina": 82,
      "power": 80,
      "guts": 80,
      "trainingScore": 0,
      "recentFormScore": 3.5,
      "recentAverageFinish": 5,
      "recentTimeIndex": 0.9,
      "lastRaceGradeScore": 2.5,
      "lastRaceGradeLabel": "L",
      "lastRaceDistance": 1400,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "2",
      "name": "ギリーズボール",
      "jockey": "西塚",
      "trainer": "手塚久",
      "runningStyle": "Senko",
      "gateNumber": 2,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 376,
      "xBuzzScore": 0,
      "predictionCount": 45,
      "realOdds": 24.5,
      "oddsSource": "official",
      "speed": 69,
      "stamina": 67,
      "power": 65,
      "guts": 66,
      "trainingScore": 0,
      "recentFormScore": -1.6,
      "recentAverageFinish": 7,
      "recentTimeIndex": -1.7,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "3",
      "name": "プレセピオ",
      "jockey": "富田",
      "trainer": "笹田",
      "runningStyle": "Nige",
      "gateNumber": 3,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 302,
      "xBuzzScore": 0,
      "predictionCount": 54,
      "realOdds": 16.4,
      "oddsSource": "official",
      "speed": 85,
      "stamina": 76,
      "power": 81,
      "guts": 81,
      "trainingScore": 0,
      "recentFormScore": 2.4,
      "recentAverageFinish": 4.4,
      "recentTimeIndex": 0.6,
      "lastRaceGradeScore": 2.5,
      "lastRaceGradeLabel": "L",
      "lastRaceDistance": 1400,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "4",
      "name": "ショウナンカリス",
      "jockey": "池添",
      "trainer": "加藤士",
      "runningStyle": "Sashi",
      "gateNumber": 4,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 3316,
      "xBuzzScore": 0,
      "predictionCount": 81,
      "realOdds": 5.3,
      "oddsSource": "official",
      "speed": 86,
      "stamina": 90,
      "power": 90,
      "guts": 88,
      "trainingScore": 0,
      "recentFormScore": 3.5,
      "recentAverageFinish": 3.2,
      "recentTimeIndex": 1,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "5",
      "name": "テイエムスティール",
      "jockey": "高杉",
      "trainer": "高橋一",
      "runningStyle": "Senko",
      "gateNumber": 5,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 2163,
      "xBuzzScore": 0,
      "predictionCount": 79,
      "realOdds": 5.7,
      "oddsSource": "official",
      "speed": 90,
      "stamina": 88,
      "power": 85,
      "guts": 89,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 2,
      "recentTimeIndex": 0.9,
      "lastRaceGradeScore": 2.5,
      "lastRaceGradeLabel": "L",
      "lastRaceDistance": 1400,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "6",
      "name": "タイニーワンダー",
      "jockey": "吉田隼",
      "trainer": "四位",
      "runningStyle": "Senko",
      "gateNumber": 6,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 100,
      "xBuzzScore": 0,
      "predictionCount": 25,
      "realOdds": 57.7,
      "oddsSource": "official",
      "speed": 69,
      "stamina": 68,
      "power": 68,
      "guts": 66,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 1.5,
      "recentTimeIndex": -5,
      "lastRaceGradeScore": 0,
      "lastRaceGradeLabel": "Maiden",
      "lastRaceDistance": 1400,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "7",
      "name": "アイニードユー",
      "jockey": "西村淳",
      "trainer": "吉村",
      "runningStyle": "Oikomi",
      "gateNumber": 7,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 669,
      "xBuzzScore": 0,
      "predictionCount": 75,
      "realOdds": 6.9,
      "oddsSource": "official",
      "speed": 87,
      "stamina": 92,
      "power": 87,
      "guts": 91,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 3.6,
      "recentTimeIndex": 1.3,
      "lastRaceGradeScore": 2.5,
      "lastRaceGradeLabel": "L",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "8",
      "name": "ルージュサウダージ",
      "jockey": "斎藤",
      "trainer": "松永幹",
      "runningStyle": "Nige",
      "gateNumber": 8,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 503,
      "xBuzzScore": 0,
      "predictionCount": 55,
      "realOdds": 16.2,
      "oddsSource": "official",
      "speed": 89,
      "stamina": 81,
      "power": 85,
      "guts": 87,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 4.8,
      "recentTimeIndex": 2.8,
      "lastRaceGradeScore": 0.5,
      "lastRaceGradeLabel": "1Win",
      "lastRaceDistance": 1200,
      "distanceChange": 200,
      "condition": 5
    },
    {
      "id": "9",
      "name": "タイセイフレッサ",
      "jockey": "小沢",
      "trainer": "斎藤誠",
      "runningStyle": "Sashi",
      "gateNumber": 9,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 88,
      "xBuzzScore": 0,
      "predictionCount": 12,
      "realOdds": 118.2,
      "oddsSource": "official",
      "speed": 74,
      "stamina": 78,
      "power": 74,
      "guts": 78,
      "trainingScore": 0,
      "recentFormScore": 3.5,
      "recentAverageFinish": 3.6,
      "recentTimeIndex": -0.7,
      "lastRaceGradeScore": 0.5,
      "lastRaceGradeLabel": "1Win",
      "lastRaceDistance": 1400,
      "distanceChange": 0,
      "condition": 5
    },
    {
      "id": "10",
      "name": "ラスティングスノー",
      "jockey": "松本",
      "trainer": "池上",
      "runningStyle": "Senko",
      "gateNumber": 10,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 156,
      "xBuzzScore": 0,
      "predictionCount": 35,
      "realOdds": 37.8,
      "oddsSource": "official",
      "speed": 76,
      "stamina": 71,
      "power": 72,
      "guts": 72,
      "trainingScore": 0,
      "recentFormScore": 0.2,
      "recentAverageFinish": 5,
      "recentTimeIndex": -2.5,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "11",
      "name": "クリエープキー",
      "jockey": "松山",
      "trainer": "牧",
      "runningStyle": "Senko",
      "gateNumber": 11,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 168,
      "xBuzzScore": 0,
      "predictionCount": 34,
      "realOdds": 38.9,
      "oddsSource": "official",
      "speed": 88,
      "stamina": 85,
      "power": 87,
      "guts": 89,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 5.2,
      "recentTimeIndex": 3.5,
      "lastRaceGradeScore": 0.5,
      "lastRaceGradeLabel": "1Win",
      "lastRaceDistance": 1200,
      "distanceChange": 200,
      "condition": 5
    },
    {
      "id": "12",
      "name": "トワニ",
      "jockey": "田山",
      "trainer": "蛯名正",
      "runningStyle": "Nige",
      "gateNumber": 12,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 308,
      "xBuzzScore": 0,
      "predictionCount": 38,
      "realOdds": 32.8,
      "oddsSource": "official",
      "speed": 85,
      "stamina": 78,
      "power": 81,
      "guts": 78,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 3.8,
      "recentTimeIndex": 0,
      "lastRaceGradeScore": 0.5,
      "lastRaceGradeLabel": "1Win",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "13",
      "name": "デアヴェローチェ",
      "jockey": "酒井",
      "trainer": "上村",
      "runningStyle": "Senko",
      "gateNumber": 13,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 1052,
      "xBuzzScore": 0,
      "predictionCount": 69,
      "realOdds": 8.8,
      "oddsSource": "official",
      "speed": 90,
      "stamina": 86,
      "power": 89,
      "guts": 86,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 2.8,
      "recentTimeIndex": 0.9,
      "lastRaceGradeScore": 2.5,
      "lastRaceGradeLabel": "L",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "14",
      "name": "コラルリーフ",
      "jockey": "鮫島駿",
      "trainer": "佐藤悠",
      "runningStyle": "Sashi",
      "gateNumber": 14,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 338,
      "xBuzzScore": 0,
      "predictionCount": 50,
      "realOdds": 19.5,
      "oddsSource": "official",
      "speed": 87,
      "stamina": 89,
      "power": 88,
      "guts": 89,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 3.2,
      "recentTimeIndex": 2.1,
      "lastRaceGradeScore": 2,
      "lastRaceGradeLabel": "OP",
      "lastRaceDistance": 1200,
      "distanceChange": 200,
      "condition": 5
    },
    {
      "id": "15",
      "name": "ローズカリス",
      "jockey": "田口",
      "trainer": "大橋",
      "runningStyle": "Nige",
      "gateNumber": 15,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 126,
      "xBuzzScore": 0,
      "predictionCount": 42,
      "realOdds": 28.2,
      "oddsSource": "official",
      "speed": 72,
      "stamina": 66,
      "power": 71,
      "guts": 71,
      "trainingScore": 0,
      "recentFormScore": 0.7,
      "recentAverageFinish": 4.4,
      "recentTimeIndex": -4.5,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "16",
      "name": "ファニーバニー",
      "jockey": "松若",
      "trainer": "杉山佳",
      "runningStyle": "Senko",
      "gateNumber": 16,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 326,
      "xBuzzScore": 0,
      "predictionCount": 50,
      "realOdds": 19.9,
      "oddsSource": "official",
      "speed": 88,
      "stamina": 83,
      "power": 83,
      "guts": 84,
      "trainingScore": 0,
      "recentFormScore": 2.7,
      "recentAverageFinish": 3.4,
      "recentTimeIndex": 1.2,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "17",
      "name": "サンアントワーヌ",
      "jockey": "荻野極",
      "trainer": "鹿戸",
      "runningStyle": "Oikomi",
      "gateNumber": 17,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 2272,
      "xBuzzScore": 0,
      "predictionCount": 80,
      "realOdds": 5.4,
      "oddsSource": "official",
      "speed": 80,
      "stamina": 87,
      "power": 84,
      "guts": 86,
      "trainingScore": 0,
      "recentFormScore": 5,
      "recentAverageFinish": 2.8,
      "recentTimeIndex": -0.3,
      "lastRaceGradeScore": 3,
      "lastRaceGradeLabel": "G3",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    },
    {
      "id": "18",
      "name": "イヌボウノウタゴエ",
      "jockey": "吉村",
      "trainer": "西田",
      "runningStyle": "Sashi",
      "gateNumber": 18,
      "sex": "F",
      "weight": 55,
      "favoriteCount": 187,
      "xBuzzScore": 0,
      "predictionCount": 38,
      "realOdds": 33.7,
      "oddsSource": "official",
      "speed": 77,
      "stamina": 81,
      "power": 77,
      "guts": 80,
      "trainingScore": 0,
      "recentFormScore": 0.3,
      "recentAverageFinish": 5,
      "recentTimeIndex": -0.3,
      "lastRaceGradeScore": 5,
      "lastRaceGradeLabel": "G1",
      "lastRaceDistance": 1600,
      "distanceChange": -200,
      "condition": 5
    }
  ]
};

export const GENERATED_COMPLETED_RACES: GeneratedReviewRace[] = [
  {
    "courseId": "nakayama-turf-1800-202606020311",
    "raceId": "202606020311",
    "label": "中山牝馬Ｓ 出馬表",
    "grade": "G3",
    "day": "Sat",
    "venue": "中山",
    "venueKey": "nakayama",
    "surface": "Turf",
    "distance": 1800,
    "straightLength": 310,
    "hashtag": "#中山牝馬Ｓ出馬表",
    "hasRace": true,
    "oddsSource": "official",
    "date": "2026-03-05",
    "result": {
      "updatedAt": "2026-03-08T07:07:41.989Z",
      "winnerHorseId": "3",
      "winnerHorseName": "エセルフリーダ",
      "top3HorseIds": [
        "3",
        "2",
        "4"
      ],
      "top3HorseNames": [
        "エセルフリーダ",
        "ビヨンドザヴァレー",
        "パラディレーヌ"
      ],
      "finishers": [
        {
          "position": 1,
          "horseId": "3",
          "externalHorseId": "2021105138",
          "gateNumber": 2,
          "horseNumber": 3,
          "name": "エセルフリーダ",
          "jockey": "武藤",
          "finishTime": "1:47.1",
          "margin": "",
          "popularity": 6,
          "odds": 15.3
        },
        {
          "position": 2,
          "horseId": "2",
          "externalHorseId": "2020103099",
          "gateNumber": 1,
          "horseNumber": 2,
          "name": "ビヨンドザヴァレー",
          "jockey": "菱田",
          "finishTime": "1:47.3",
          "margin": "1.1/4",
          "popularity": 11,
          "odds": 28.8
        },
        {
          "position": 3,
          "horseId": "4",
          "externalHorseId": "2022103546",
          "gateNumber": 2,
          "horseNumber": 4,
          "name": "パラディレーヌ",
          "jockey": "岩田望",
          "finishTime": "1:47.3",
          "margin": "ハナ",
          "popularity": 3,
          "odds": 5.3
        },
        {
          "position": 4,
          "horseId": "13",
          "externalHorseId": "2022103205",
          "gateNumber": 7,
          "horseNumber": 13,
          "name": "エリカエクスプレス",
          "jockey": "武豊",
          "finishTime": "1:47.3",
          "margin": "クビ",
          "popularity": 4,
          "odds": 5.5
        },
        {
          "position": 5,
          "horseId": "14",
          "externalHorseId": "2021100244",
          "gateNumber": 7,
          "horseNumber": 14,
          "name": "ニシノティアモ",
          "jockey": "津村",
          "finishTime": "1:47.3",
          "margin": "クビ",
          "popularity": 2,
          "odds": 4.8
        },
        {
          "position": 6,
          "horseId": "16",
          "externalHorseId": "2022105346",
          "gateNumber": 8,
          "horseNumber": 16,
          "name": "レーゼドラマ",
          "jockey": "丹内",
          "finishTime": "1:47.4",
          "margin": "クビ",
          "popularity": 7,
          "odds": 17
        },
        {
          "position": 7,
          "horseId": "9",
          "externalHorseId": "2021105743",
          "gateNumber": 5,
          "horseNumber": 9,
          "name": "ステレンボッシュ",
          "jockey": "ルメー",
          "finishTime": "1:47.7",
          "margin": "1.3/4",
          "popularity": 9,
          "odds": 23.4
        },
        {
          "position": 8,
          "horseId": "15",
          "externalHorseId": "2022102296",
          "gateNumber": 8,
          "horseNumber": 15,
          "name": "ケリフレッドアスク",
          "jockey": "佐々木",
          "finishTime": "1:47.7",
          "margin": "ハナ",
          "popularity": 13,
          "odds": 61.4
        },
        {
          "position": 9,
          "horseId": "12",
          "externalHorseId": "2020103577",
          "gateNumber": 6,
          "horseNumber": 12,
          "name": "ポルカリズム",
          "jockey": "三浦",
          "finishTime": "1:47.7",
          "margin": "ハナ",
          "popularity": 10,
          "odds": 25.2
        },
        {
          "position": 10,
          "horseId": "5",
          "externalHorseId": "2021107179",
          "gateNumber": 3,
          "horseNumber": 5,
          "name": "ボンドガール",
          "jockey": "岩田康",
          "finishTime": "1:47.7",
          "margin": "アタマ",
          "popularity": 5,
          "odds": 13
        },
        {
          "position": 11,
          "horseId": "6",
          "externalHorseId": "2020103304",
          "gateNumber": 3,
          "horseNumber": 6,
          "name": "アンリーロード",
          "jockey": "石川",
          "finishTime": "1:47.8",
          "margin": "1/2",
          "popularity": 16,
          "odds": 218.9
        },
        {
          "position": 12,
          "horseId": "7",
          "externalHorseId": "2021105581",
          "gateNumber": 4,
          "horseNumber": 7,
          "name": "フレミングフープ",
          "jockey": "杉原",
          "finishTime": "1:47.9",
          "margin": "クビ",
          "popularity": 8,
          "odds": 17.2
        },
        {
          "position": 13,
          "horseId": "10",
          "externalHorseId": "2021105738",
          "gateNumber": 5,
          "horseNumber": 10,
          "name": "アンゴラブラック",
          "jockey": "戸崎圭",
          "finishTime": "1:48.4",
          "margin": "3",
          "popularity": 1,
          "odds": 4.2
        },
        {
          "position": 14,
          "horseId": "11",
          "externalHorseId": "2019105768",
          "gateNumber": 6,
          "horseNumber": 11,
          "name": "フィールシンパシー",
          "jockey": "横山琉",
          "finishTime": "1:48.5",
          "margin": "1/2",
          "popularity": 15,
          "odds": 136.2
        },
        {
          "position": 15,
          "horseId": "1",
          "externalHorseId": "2022101250",
          "gateNumber": 1,
          "horseNumber": 1,
          "name": "クリノメイ",
          "jockey": "横山典",
          "finishTime": "1:48.8",
          "margin": "1.3/4",
          "popularity": 12,
          "odds": 36.7
        },
        {
          "position": 16,
          "horseId": "8",
          "externalHorseId": "2021105228",
          "gateNumber": 4,
          "horseNumber": 8,
          "name": "レディーヴァリュー",
          "jockey": "団野",
          "finishTime": "1:48.9",
          "margin": "1/2",
          "popularity": 14,
          "odds": 77.9
        }
      ]
    },
    "review": {
      "updatedAt": "2026-03-08T07:08:40.073Z",
      "summary": "エセルフリーダは条件が噛み合って突き抜けた。距離短縮で追走負荷が軽くなった、先行力を生かしやすい舞台だった、内目の枠からロスなく運べた。",
      "xPostText": "【中山牝馬Ｓ回顧】1着 エセルフリーダ(6番人気 15.3倍) / 2着 ビヨンドザヴァレー / 3着 パラディレーヌ。エセルフリーダは条件が噛み合って突き抜けた。距離短縮で追走負荷が軽くなった、先行力を生かしやすい舞台だった、内目の枠からロスなく運べた。 #中山牝馬Ｓ",
      "reasons": [
        "距離短縮で追走負荷が軽くなった",
        "先行力を生かしやすい舞台だった",
        "内目の枠からロスなく運べた"
      ]
    },
    "horses": [
      {
        "id": "1",
        "name": "クリノメイ",
        "jockey": "横山典",
        "trainer": "須貝",
        "runningStyle": "Sashi",
        "gateNumber": 1,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 253,
        "xBuzzScore": 0,
        "predictionCount": 36,
        "realOdds": 36.7,
        "oddsSource": "official",
        "speed": 56,
        "stamina": 60,
        "power": 56,
        "guts": 60,
        "trainingScore": 0,
        "recentFormScore": -1.2,
        "recentAverageFinish": 7.6,
        "recentTimeIndex": -5,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "2",
        "name": "ビヨンドザヴァレー",
        "jockey": "菱田",
        "trainer": "橋口",
        "runningStyle": "Nige",
        "gateNumber": 2,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 309,
        "xBuzzScore": 0,
        "predictionCount": 41,
        "realOdds": 28.8,
        "oddsSource": "official",
        "speed": 63,
        "stamina": 55,
        "power": 58,
        "guts": 57,
        "trainingScore": 0,
        "recentFormScore": -1.4,
        "recentAverageFinish": 7.8,
        "recentTimeIndex": -3.3,
        "lastRaceGradeScore": 2,
        "lastRaceGradeLabel": "OP",
        "lastRaceDistance": 1800,
        "distanceChange": 0,
        "condition": 5
      },
      {
        "id": "3",
        "name": "エセルフリーダ",
        "jockey": "武藤",
        "trainer": "武藤",
        "runningStyle": "Senko",
        "gateNumber": 3,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 487,
        "xBuzzScore": 0,
        "predictionCount": 56,
        "realOdds": 15.3,
        "oddsSource": "official",
        "speed": 81,
        "stamina": 77,
        "power": 79,
        "guts": 81,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 5,
        "recentTimeIndex": -0.4,
        "lastRaceGradeScore": 1.5,
        "lastRaceGradeLabel": "3Win",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "4",
        "name": "パラディレーヌ",
        "jockey": "岩田望",
        "trainer": "千田",
        "runningStyle": "Sashi",
        "gateNumber": 4,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 2217,
        "xBuzzScore": 0,
        "predictionCount": 81,
        "realOdds": 5.3,
        "oddsSource": "official",
        "speed": 89,
        "stamina": 89,
        "power": 87,
        "guts": 90,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 4.3,
        "recentTimeIndex": 0.8,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 2200,
        "distanceChange": -400,
        "condition": 5
      },
      {
        "id": "5",
        "name": "ボンドガール",
        "jockey": "岩田康",
        "trainer": "手塚久",
        "runningStyle": "Senko",
        "gateNumber": 5,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 857,
        "xBuzzScore": 0,
        "predictionCount": 60,
        "realOdds": 13,
        "oddsSource": "official",
        "speed": 85,
        "stamina": 85,
        "power": 86,
        "guts": 83,
        "trainingScore": 0,
        "recentFormScore": 3.4,
        "recentAverageFinish": 7,
        "recentTimeIndex": 2.6,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "6",
        "name": "アンリーロード",
        "jockey": "石川",
        "trainer": "茶木",
        "runningStyle": "Senko",
        "gateNumber": 6,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 49,
        "xBuzzScore": 0,
        "predictionCount": 12,
        "realOdds": 218.9,
        "oddsSource": "official",
        "speed": 60,
        "stamina": 57,
        "power": 58,
        "guts": 59,
        "trainingScore": 0,
        "recentFormScore": -5,
        "recentAverageFinish": 10.8,
        "recentTimeIndex": -0.4,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "7",
        "name": "フレミングフープ",
        "jockey": "杉原",
        "trainer": "友道",
        "runningStyle": "Senko",
        "gateNumber": 7,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 656,
        "xBuzzScore": 0,
        "predictionCount": 53,
        "realOdds": 17.2,
        "oddsSource": "official",
        "speed": 86,
        "stamina": 85,
        "power": 84,
        "guts": 85,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 2.4,
        "recentTimeIndex": 0,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "8",
        "name": "レディーヴァリュー",
        "jockey": "団野",
        "trainer": "小林",
        "runningStyle": "Senko",
        "gateNumber": 8,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 72,
        "xBuzzScore": 0,
        "predictionCount": 18,
        "realOdds": 77.9,
        "oddsSource": "official",
        "speed": 77,
        "stamina": 76,
        "power": 74,
        "guts": 74,
        "trainingScore": 0,
        "recentFormScore": 0.6,
        "recentAverageFinish": 4.5,
        "recentTimeIndex": -0.9,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "9",
        "name": "ステレンボッシュ",
        "jockey": "ルメール",
        "trainer": "宮田",
        "runningStyle": "Sashi",
        "gateNumber": 9,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 327,
        "xBuzzScore": 0,
        "predictionCount": 46,
        "realOdds": 23.4,
        "oddsSource": "official",
        "speed": 64,
        "stamina": 68,
        "power": 64,
        "guts": 67,
        "trainingScore": 0,
        "recentFormScore": -5,
        "recentAverageFinish": 11.5,
        "recentTimeIndex": 0.5,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 2200,
        "distanceChange": -400,
        "condition": 5
      },
      {
        "id": "10",
        "name": "アンゴラブラック",
        "jockey": "戸崎圭",
        "trainer": "尾関",
        "runningStyle": "Senko",
        "gateNumber": 10,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 4486,
        "xBuzzScore": 0,
        "predictionCount": 86,
        "realOdds": 4.2,
        "oddsSource": "official",
        "speed": 86,
        "stamina": 87,
        "power": 89,
        "guts": 86,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 1.4,
        "recentTimeIndex": 0.7,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "11",
        "name": "フィールシンパシー",
        "jockey": "横山琉",
        "trainer": "小島",
        "runningStyle": "Senko",
        "gateNumber": 11,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 82,
        "xBuzzScore": 0,
        "predictionCount": 12,
        "realOdds": 136.2,
        "oddsSource": "official",
        "speed": 65,
        "stamina": 62,
        "power": 65,
        "guts": 61,
        "trainingScore": 0,
        "recentFormScore": -4.9,
        "recentAverageFinish": 10.8,
        "recentTimeIndex": 1,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "12",
        "name": "ポルカリズム",
        "jockey": "三浦",
        "trainer": "中内田",
        "runningStyle": "Sashi",
        "gateNumber": 12,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 301,
        "xBuzzScore": 0,
        "predictionCount": 44,
        "realOdds": 25.2,
        "oddsSource": "official",
        "speed": 88,
        "stamina": 90,
        "power": 88,
        "guts": 90,
        "trainingScore": 0,
        "recentFormScore": 4.3,
        "recentAverageFinish": 6,
        "recentTimeIndex": 4.4,
        "lastRaceGradeScore": 1.5,
        "lastRaceGradeLabel": "3Win",
        "lastRaceDistance": 1600,
        "distanceChange": 200,
        "condition": 5
      },
      {
        "id": "13",
        "name": "エリカエクスプレス",
        "jockey": "武豊",
        "trainer": "杉山晴",
        "runningStyle": "Sashi",
        "gateNumber": 13,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 1357,
        "xBuzzScore": 0,
        "predictionCount": 80,
        "realOdds": 5.5,
        "oddsSource": "official",
        "speed": 71,
        "stamina": 72,
        "power": 72,
        "guts": 71,
        "trainingScore": 0,
        "recentFormScore": -3.2,
        "recentAverageFinish": 8.8,
        "recentTimeIndex": 0.7,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 2200,
        "distanceChange": -400,
        "condition": 5
      },
      {
        "id": "14",
        "name": "ニシノティアモ",
        "jockey": "津村",
        "trainer": "上原佑",
        "runningStyle": "Senko",
        "gateNumber": 14,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 1955,
        "xBuzzScore": 0,
        "predictionCount": 83,
        "realOdds": 4.8,
        "oddsSource": "official",
        "speed": 89,
        "stamina": 89,
        "power": 90,
        "guts": 89,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 1,
        "recentTimeIndex": 0.9,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "15",
        "name": "ケリフレッドアスク",
        "jockey": "佐々木",
        "trainer": "藤原",
        "runningStyle": "Sashi",
        "gateNumber": 15,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 77,
        "xBuzzScore": 0,
        "predictionCount": 23,
        "realOdds": 61.4,
        "oddsSource": "official",
        "speed": 72,
        "stamina": 76,
        "power": 72,
        "guts": 75,
        "trainingScore": 0,
        "recentFormScore": -2,
        "recentAverageFinish": 7.5,
        "recentTimeIndex": 0.7,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 2200,
        "distanceChange": -400,
        "condition": 5
      },
      {
        "id": "16",
        "name": "レーゼドラマ",
        "jockey": "丹内",
        "trainer": "辻野",
        "runningStyle": "Sashi",
        "gateNumber": 16,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 332,
        "xBuzzScore": 0,
        "predictionCount": 54,
        "realOdds": 17,
        "oddsSource": "official",
        "speed": 60,
        "stamina": 63,
        "power": 62,
        "guts": 62,
        "trainingScore": 0,
        "recentFormScore": -0.2,
        "recentAverageFinish": 11,
        "recentTimeIndex": -1.8,
        "lastRaceGradeScore": 2,
        "lastRaceGradeLabel": "OP",
        "lastRaceDistance": 2000,
        "distanceChange": -200,
        "condition": 5
      }
    ]
  },
  {
    "courseId": "hanshin-turf-1400-202609010511",
    "raceId": "202609010511",
    "label": "フィリーズレビュー 出馬表",
    "grade": "G2",
    "day": "Sat",
    "venue": "阪神",
    "venueKey": "hanshin",
    "surface": "Turf",
    "distance": 1400,
    "straightLength": 473.6,
    "hashtag": "#フィリーズレビュー出馬表",
    "hasRace": true,
    "oddsSource": "official",
    "date": "2026-03-05",
    "result": {
      "updatedAt": "2026-03-08T07:07:42.202Z",
      "winnerHorseId": "2",
      "winnerHorseName": "ギリーズボール",
      "top3HorseIds": [
        "2",
        "17",
        "7"
      ],
      "top3HorseNames": [
        "ギリーズボール",
        "サンアントワーヌ",
        "アイニードユー"
      ],
      "finishers": [
        {
          "position": 1,
          "horseId": "2",
          "externalHorseId": "2023107187",
          "gateNumber": 1,
          "horseNumber": 2,
          "name": "ギリーズボール",
          "jockey": "西塚",
          "finishTime": "1:20.6",
          "margin": "",
          "popularity": 10,
          "odds": 24.5
        },
        {
          "position": 2,
          "horseId": "17",
          "externalHorseId": "2023107020",
          "gateNumber": 8,
          "horseNumber": 17,
          "name": "サンアントワーヌ",
          "jockey": "荻野極",
          "finishTime": "1:20.9",
          "margin": "1.3/4",
          "popularity": 2,
          "odds": 5.4
        },
        {
          "position": 3,
          "horseId": "7",
          "externalHorseId": "2023101159",
          "gateNumber": 4,
          "horseNumber": 7,
          "name": "アイニードユー",
          "jockey": "西村淳",
          "finishTime": "1:20.9",
          "margin": "ハナ",
          "popularity": 4,
          "odds": 6.9
        },
        {
          "position": 4,
          "horseId": "13",
          "externalHorseId": "2023107264",
          "gateNumber": 7,
          "horseNumber": 13,
          "name": "デアヴェローチェ",
          "jockey": "酒井",
          "finishTime": "1:20.9",
          "margin": "ハナ",
          "popularity": 5,
          "odds": 8.8
        },
        {
          "position": 5,
          "horseId": "3",
          "externalHorseId": "2023103503",
          "gateNumber": 2,
          "horseNumber": 3,
          "name": "プレセピオ",
          "jockey": "富田",
          "finishTime": "1:21.0",
          "margin": "1/2",
          "popularity": 7,
          "odds": 16.4
        },
        {
          "position": 6,
          "horseId": "1",
          "externalHorseId": "2023103247",
          "gateNumber": 1,
          "horseNumber": 1,
          "name": "フルールジェンヌ",
          "jockey": "永島",
          "finishTime": "1:21.0",
          "margin": "クビ",
          "popularity": 17,
          "odds": 92.3
        },
        {
          "position": 7,
          "horseId": "12",
          "externalHorseId": "2023102694",
          "gateNumber": 6,
          "horseNumber": 12,
          "name": "トワニ",
          "jockey": "田山",
          "finishTime": "1:21.1",
          "margin": "クビ",
          "popularity": 12,
          "odds": 32.8
        },
        {
          "position": 8,
          "horseId": "4",
          "externalHorseId": "2023105347",
          "gateNumber": 2,
          "horseNumber": 4,
          "name": "ショウナンカリス",
          "jockey": "池添",
          "finishTime": "1:21.2",
          "margin": "3/4",
          "popularity": 1,
          "odds": 5.3
        },
        {
          "position": 9,
          "horseId": "18",
          "externalHorseId": "2023103086",
          "gateNumber": 8,
          "horseNumber": 18,
          "name": "イヌボウノウタゴエ",
          "jockey": "吉村",
          "finishTime": "1:21.2",
          "margin": "ハナ",
          "popularity": 13,
          "odds": 33.7
        },
        {
          "position": 10,
          "horseId": "14",
          "externalHorseId": "2023106185",
          "gateNumber": 7,
          "horseNumber": 14,
          "name": "コラルリーフ",
          "jockey": "鮫島駿",
          "finishTime": "1:21.3",
          "margin": "3/4",
          "popularity": 8,
          "odds": 19.5
        },
        {
          "position": 11,
          "horseId": "5",
          "externalHorseId": "2023104034",
          "gateNumber": 3,
          "horseNumber": 5,
          "name": "テイエムスティール",
          "jockey": "高杉",
          "finishTime": "1:21.4",
          "margin": "1/2",
          "popularity": 3,
          "odds": 5.7
        },
        {
          "position": 12,
          "horseId": "9",
          "externalHorseId": "2023100914",
          "gateNumber": 5,
          "horseNumber": 9,
          "name": "タイセイフレッサ",
          "jockey": "小沢",
          "finishTime": "1:21.5",
          "margin": "1/2",
          "popularity": 18,
          "odds": 118.2
        },
        {
          "position": 13,
          "horseId": "6",
          "externalHorseId": "2023105027",
          "gateNumber": 3,
          "horseNumber": 6,
          "name": "タイニーワンダー",
          "jockey": "吉田隼",
          "finishTime": "1:21.6",
          "margin": "クビ",
          "popularity": 16,
          "odds": 57.7
        },
        {
          "position": 14,
          "horseId": "16",
          "externalHorseId": "2023105277",
          "gateNumber": 8,
          "horseNumber": 16,
          "name": "ファニーバニー",
          "jockey": "松若",
          "finishTime": "1:21.7",
          "margin": "3/4",
          "popularity": 9,
          "odds": 19.9
        },
        {
          "position": 15,
          "horseId": "8",
          "externalHorseId": "2023103721",
          "gateNumber": 4,
          "horseNumber": 8,
          "name": "ルージュサウダージ",
          "jockey": "斎藤",
          "finishTime": "1:21.8",
          "margin": "3/4",
          "popularity": 6,
          "odds": 16.2
        },
        {
          "position": 16,
          "horseId": "15",
          "externalHorseId": "2023102991",
          "gateNumber": 7,
          "horseNumber": 15,
          "name": "ローズカリス",
          "jockey": "田口",
          "finishTime": "1:22.0",
          "margin": "1",
          "popularity": 11,
          "odds": 28.2
        },
        {
          "position": 17,
          "horseId": "10",
          "externalHorseId": "2023103293",
          "gateNumber": 5,
          "horseNumber": 10,
          "name": "ラスティングスノー",
          "jockey": "松本",
          "finishTime": "1:22.6",
          "margin": "3.1/2",
          "popularity": 14,
          "odds": 37.8
        },
        {
          "position": 18,
          "horseId": "11",
          "externalHorseId": "2023103355",
          "gateNumber": 6,
          "horseNumber": 11,
          "name": "クリエープキー",
          "jockey": "松山",
          "finishTime": "1:23.0",
          "margin": "2.1/2",
          "popularity": 15,
          "odds": 38.9
        }
      ]
    },
    "review": {
      "updatedAt": "2026-03-08T07:08:40.289Z",
      "summary": "ギリーズボールは能力と条件が噛み合って押し切った。距離短縮で追走負荷が軽くなった、近走の能力水準がこの相手では上位だった、人気以上に能力を出せる下地があった。",
      "xPostText": "【フィリーズレビュー回顧】1着 ギリーズボール(10番人気 24.5倍) / 2着 サンアントワーヌ / 3着 アイニードユー。ギリーズボールは能力と条件が噛み合って押し切った。距離短縮で追走負荷が軽くなった、近走の能力水準がこの相手では上位だった、人気以上に能力を出せる下地があった。 #フィリーズレビュー",
      "reasons": [
        "距離短縮で追走負荷が軽くなった",
        "近走の能力水準がこの相手では上位だった",
        "人気以上に能力を出せる下地があった"
      ]
    },
    "horses": [
      {
        "id": "1",
        "name": "フルールジェンヌ",
        "jockey": "永島",
        "trainer": "鈴木孝",
        "runningStyle": "Sashi",
        "gateNumber": 1,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 70,
        "xBuzzScore": 0,
        "predictionCount": 14,
        "realOdds": 92.3,
        "oddsSource": "official",
        "speed": 80,
        "stamina": 82,
        "power": 80,
        "guts": 80,
        "trainingScore": 0,
        "recentFormScore": 3.5,
        "recentAverageFinish": 5,
        "recentTimeIndex": 0.9,
        "lastRaceGradeScore": 2.5,
        "lastRaceGradeLabel": "L",
        "lastRaceDistance": 1400,
        "distanceChange": 0,
        "condition": 5
      },
      {
        "id": "2",
        "name": "ギリーズボール",
        "jockey": "西塚",
        "trainer": "手塚久",
        "runningStyle": "Senko",
        "gateNumber": 2,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 376,
        "xBuzzScore": 0,
        "predictionCount": 45,
        "realOdds": 24.5,
        "oddsSource": "official",
        "speed": 69,
        "stamina": 67,
        "power": 65,
        "guts": 66,
        "trainingScore": 0,
        "recentFormScore": -1.6,
        "recentAverageFinish": 7,
        "recentTimeIndex": -1.7,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "3",
        "name": "プレセピオ",
        "jockey": "富田",
        "trainer": "笹田",
        "runningStyle": "Nige",
        "gateNumber": 3,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 302,
        "xBuzzScore": 0,
        "predictionCount": 54,
        "realOdds": 16.4,
        "oddsSource": "official",
        "speed": 85,
        "stamina": 76,
        "power": 81,
        "guts": 81,
        "trainingScore": 0,
        "recentFormScore": 2.4,
        "recentAverageFinish": 4.4,
        "recentTimeIndex": 0.6,
        "lastRaceGradeScore": 2.5,
        "lastRaceGradeLabel": "L",
        "lastRaceDistance": 1400,
        "distanceChange": 0,
        "condition": 5
      },
      {
        "id": "4",
        "name": "ショウナンカリス",
        "jockey": "池添",
        "trainer": "加藤士",
        "runningStyle": "Sashi",
        "gateNumber": 4,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 3316,
        "xBuzzScore": 0,
        "predictionCount": 81,
        "realOdds": 5.3,
        "oddsSource": "official",
        "speed": 86,
        "stamina": 90,
        "power": 90,
        "guts": 88,
        "trainingScore": 0,
        "recentFormScore": 3.5,
        "recentAverageFinish": 3.2,
        "recentTimeIndex": 1,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "5",
        "name": "テイエムスティール",
        "jockey": "高杉",
        "trainer": "高橋一",
        "runningStyle": "Senko",
        "gateNumber": 5,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 2163,
        "xBuzzScore": 0,
        "predictionCount": 79,
        "realOdds": 5.7,
        "oddsSource": "official",
        "speed": 90,
        "stamina": 88,
        "power": 85,
        "guts": 89,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 2,
        "recentTimeIndex": 0.9,
        "lastRaceGradeScore": 2.5,
        "lastRaceGradeLabel": "L",
        "lastRaceDistance": 1400,
        "distanceChange": 0,
        "condition": 5
      },
      {
        "id": "6",
        "name": "タイニーワンダー",
        "jockey": "吉田隼",
        "trainer": "四位",
        "runningStyle": "Senko",
        "gateNumber": 6,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 100,
        "xBuzzScore": 0,
        "predictionCount": 25,
        "realOdds": 57.7,
        "oddsSource": "official",
        "speed": 69,
        "stamina": 68,
        "power": 68,
        "guts": 66,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 1.5,
        "recentTimeIndex": -5,
        "lastRaceGradeScore": 0,
        "lastRaceGradeLabel": "Maiden",
        "lastRaceDistance": 1400,
        "distanceChange": 0,
        "condition": 5
      },
      {
        "id": "7",
        "name": "アイニードユー",
        "jockey": "西村淳",
        "trainer": "吉村",
        "runningStyle": "Oikomi",
        "gateNumber": 7,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 669,
        "xBuzzScore": 0,
        "predictionCount": 75,
        "realOdds": 6.9,
        "oddsSource": "official",
        "speed": 87,
        "stamina": 92,
        "power": 87,
        "guts": 91,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 3.6,
        "recentTimeIndex": 1.3,
        "lastRaceGradeScore": 2.5,
        "lastRaceGradeLabel": "L",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "8",
        "name": "ルージュサウダージ",
        "jockey": "斎藤",
        "trainer": "松永幹",
        "runningStyle": "Nige",
        "gateNumber": 8,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 503,
        "xBuzzScore": 0,
        "predictionCount": 55,
        "realOdds": 16.2,
        "oddsSource": "official",
        "speed": 89,
        "stamina": 81,
        "power": 85,
        "guts": 87,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 4.8,
        "recentTimeIndex": 2.8,
        "lastRaceGradeScore": 0.5,
        "lastRaceGradeLabel": "1Win",
        "lastRaceDistance": 1200,
        "distanceChange": 200,
        "condition": 5
      },
      {
        "id": "9",
        "name": "タイセイフレッサ",
        "jockey": "小沢",
        "trainer": "斎藤誠",
        "runningStyle": "Sashi",
        "gateNumber": 9,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 88,
        "xBuzzScore": 0,
        "predictionCount": 12,
        "realOdds": 118.2,
        "oddsSource": "official",
        "speed": 74,
        "stamina": 78,
        "power": 74,
        "guts": 78,
        "trainingScore": 0,
        "recentFormScore": 3.5,
        "recentAverageFinish": 3.6,
        "recentTimeIndex": -0.7,
        "lastRaceGradeScore": 0.5,
        "lastRaceGradeLabel": "1Win",
        "lastRaceDistance": 1400,
        "distanceChange": 0,
        "condition": 5
      },
      {
        "id": "10",
        "name": "ラスティングスノー",
        "jockey": "松本",
        "trainer": "池上",
        "runningStyle": "Senko",
        "gateNumber": 10,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 156,
        "xBuzzScore": 0,
        "predictionCount": 35,
        "realOdds": 37.8,
        "oddsSource": "official",
        "speed": 76,
        "stamina": 71,
        "power": 72,
        "guts": 72,
        "trainingScore": 0,
        "recentFormScore": 0.2,
        "recentAverageFinish": 5,
        "recentTimeIndex": -2.5,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "11",
        "name": "クリエープキー",
        "jockey": "松山",
        "trainer": "牧",
        "runningStyle": "Senko",
        "gateNumber": 11,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 168,
        "xBuzzScore": 0,
        "predictionCount": 34,
        "realOdds": 38.9,
        "oddsSource": "official",
        "speed": 88,
        "stamina": 85,
        "power": 87,
        "guts": 89,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 5.2,
        "recentTimeIndex": 3.5,
        "lastRaceGradeScore": 0.5,
        "lastRaceGradeLabel": "1Win",
        "lastRaceDistance": 1200,
        "distanceChange": 200,
        "condition": 5
      },
      {
        "id": "12",
        "name": "トワニ",
        "jockey": "田山",
        "trainer": "蛯名正",
        "runningStyle": "Nige",
        "gateNumber": 12,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 308,
        "xBuzzScore": 0,
        "predictionCount": 38,
        "realOdds": 32.8,
        "oddsSource": "official",
        "speed": 85,
        "stamina": 78,
        "power": 81,
        "guts": 78,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 3.8,
        "recentTimeIndex": 0,
        "lastRaceGradeScore": 0.5,
        "lastRaceGradeLabel": "1Win",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "13",
        "name": "デアヴェローチェ",
        "jockey": "酒井",
        "trainer": "上村",
        "runningStyle": "Senko",
        "gateNumber": 13,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 1052,
        "xBuzzScore": 0,
        "predictionCount": 69,
        "realOdds": 8.8,
        "oddsSource": "official",
        "speed": 90,
        "stamina": 86,
        "power": 89,
        "guts": 86,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 2.8,
        "recentTimeIndex": 0.9,
        "lastRaceGradeScore": 2.5,
        "lastRaceGradeLabel": "L",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "14",
        "name": "コラルリーフ",
        "jockey": "鮫島駿",
        "trainer": "佐藤悠",
        "runningStyle": "Sashi",
        "gateNumber": 14,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 338,
        "xBuzzScore": 0,
        "predictionCount": 50,
        "realOdds": 19.5,
        "oddsSource": "official",
        "speed": 87,
        "stamina": 89,
        "power": 88,
        "guts": 89,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 3.2,
        "recentTimeIndex": 2.1,
        "lastRaceGradeScore": 2,
        "lastRaceGradeLabel": "OP",
        "lastRaceDistance": 1200,
        "distanceChange": 200,
        "condition": 5
      },
      {
        "id": "15",
        "name": "ローズカリス",
        "jockey": "田口",
        "trainer": "大橋",
        "runningStyle": "Nige",
        "gateNumber": 15,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 126,
        "xBuzzScore": 0,
        "predictionCount": 42,
        "realOdds": 28.2,
        "oddsSource": "official",
        "speed": 72,
        "stamina": 66,
        "power": 71,
        "guts": 71,
        "trainingScore": 0,
        "recentFormScore": 0.7,
        "recentAverageFinish": 4.4,
        "recentTimeIndex": -4.5,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "16",
        "name": "ファニーバニー",
        "jockey": "松若",
        "trainer": "杉山佳",
        "runningStyle": "Senko",
        "gateNumber": 16,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 326,
        "xBuzzScore": 0,
        "predictionCount": 50,
        "realOdds": 19.9,
        "oddsSource": "official",
        "speed": 88,
        "stamina": 83,
        "power": 83,
        "guts": 84,
        "trainingScore": 0,
        "recentFormScore": 2.7,
        "recentAverageFinish": 3.4,
        "recentTimeIndex": 1.2,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "17",
        "name": "サンアントワーヌ",
        "jockey": "荻野極",
        "trainer": "鹿戸",
        "runningStyle": "Oikomi",
        "gateNumber": 17,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 2272,
        "xBuzzScore": 0,
        "predictionCount": 80,
        "realOdds": 5.4,
        "oddsSource": "official",
        "speed": 80,
        "stamina": 87,
        "power": 84,
        "guts": 86,
        "trainingScore": 0,
        "recentFormScore": 5,
        "recentAverageFinish": 2.8,
        "recentTimeIndex": -0.3,
        "lastRaceGradeScore": 3,
        "lastRaceGradeLabel": "G3",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      },
      {
        "id": "18",
        "name": "イヌボウノウタゴエ",
        "jockey": "吉村",
        "trainer": "西田",
        "runningStyle": "Sashi",
        "gateNumber": 18,
        "sex": "F",
        "weight": 55,
        "favoriteCount": 187,
        "xBuzzScore": 0,
        "predictionCount": 38,
        "realOdds": 33.7,
        "oddsSource": "official",
        "speed": 77,
        "stamina": 81,
        "power": 77,
        "guts": 80,
        "trainingScore": 0,
        "recentFormScore": 0.3,
        "recentAverageFinish": 5,
        "recentTimeIndex": -0.3,
        "lastRaceGradeScore": 5,
        "lastRaceGradeLabel": "G1",
        "lastRaceDistance": 1600,
        "distanceChange": -200,
        "condition": 5
      }
    ]
  }
];

export const GENERATED_ARCHIVED_RACES: GeneratedReviewRace[] = [];
