// Auto-generated by scripts/weekly-keiba-update.mjs
// Do not edit manually.

export const NETKEIBA_DATA_GENERATED_AT = "2026-06-03T08:11:39.732Z";

export const JOCKEY_WIN_RATE: Record<string, number> = {
  "C.ルメール": 25.2,
  "川田将雅": 24.8,
  "戸崎圭太": 15.8,
  "坂井瑠星": 14.9,
  "丹内祐次": 14.5
};

export const TRAINER_WIN_RATE: Record<string, number> = {
  "福永祐一": 22.9,
  "矢作芳人": 20.9,
  "斉藤崇史": 18.8,
  "上村洋行": 15.8
};
